// 施工実績データ（編集用）。id は詳細ページURL（WorkDetail.dc.html?id=）と画像枠IDに使われます。
// img: 一覧・詳細のメイン写真 / gallery: 詳細ページ下部の写真3枚（images/ フォルダ内）
window.KANAME_PROJECTS = [
  { id: 1, name: '〇〇駅前商業ビル新築工事', type: '商業施設', loc: '東京都中央区', year: '2026年3月', cat: '建築工事', ph: '商業ビル外観',
    img: 'images/glass-building.jpg', gallery: ['images/steel-frame.jpg', 'images/team-review.jpg', 'images/handshake.jpg'],
    structure: '鉄骨造 地上8階', area: '6,420㎡', period: '2024年9月〜2026年3月', client: '〇〇不動産株式会社',
    summary: '駅前の再開発区域に建つ複合商業ビルの新築工事です。低層階に物販・飲食店舗、上層階にオフィスを配置し、歩行者の多い立地で安全動線を確保しながら施工を進めました。',
    points: ['夜間搬入を中心とした工程計画で、周辺交通への影響を最小限に抑制', 'BIMによる設備干渉チェックで手戻りを削減', '外装カーテンウォールの精度管理を自社で徹底'] },
  { id: 2, name: '〇〇レジデンス新築工事', type: '集合住宅', loc: '神奈川県横浜市', year: '2025年11月', cat: '建築工事', ph: '集合住宅の外観',
    img: 'images/crane-building.jpg', gallery: ['images/steel-scaffold.jpg', 'images/meeting-helmet.jpg', 'images/engineers-laptop.jpg'],
    structure: '鉄筋コンクリート造 地上10階', area: '4,860㎡', period: '2024年6月〜2025年11月', client: '〇〇ホーム株式会社',
    summary: '全56戸の分譲マンション新築工事です。住宅街に隣接する敷地のため、騒音・振動対策と近隣への丁寧な説明を重ねながら工事を進めました。',
    points: ['低騒音型重機の採用と作業時間帯の調整', 'コンクリート打設ごとの強度試験と記録の共有', '共用部仕上げのモックアップ確認'] },
  { id: 3, name: '〇〇本社オフィス改修工事', type: 'オフィス', loc: '東京都港区', year: '2025年8月', cat: '改修・リフォーム', ph: '改修後のオフィス内観',
    img: 'images/team-office.jpg', gallery: ['images/planning-desk.jpg', 'images/consultation.jpg', 'images/team-review.jpg'],
    structure: '鉄骨鉄筋コンクリート造 3フロア', area: '2,150㎡', period: '2025年3月〜2025年8月', client: '株式会社〇〇',
    summary: '築30年のオフィスビル3フロアの全面改修工事です。業務を継続しながらの居ながら施工で、フロアごとに段階的に工事を進めました。',
    points: ['フロア単位の段階施工で業務停止期間ゼロ', '空調・照明設備の更新による省エネ化', '防音・防塵養生の徹底'] },
  { id: 4, name: '〇〇クリニックモール新築工事', type: '医療施設', loc: '埼玉県さいたま市', year: '2025年5月', cat: '建築工事', ph: '医療施設のエントランス',
    img: 'images/tower-cranes.jpg', gallery: ['images/steel-frame.jpg', 'images/meeting-helmet.jpg', 'images/team.jpg'],
    structure: '鉄骨造 地上3階', area: '1,980㎡', period: '2024年8月〜2025年5月', client: '医療法人〇〇会',
    summary: '内科・小児科・調剤薬局などが入居するクリニックモールの新築工事です。医療機器の設置要件に合わせた床・天井の補強や、バリアフリー動線を丁寧に計画しました。',
    points: ['医療機器の荷重・振動条件に応じた構造補強', '多目的トイレ・スロープなどのバリアフリー対応', '入居テナントごとの内装工事を一括管理'] },
  { id: 5, name: '市道〇〇線道路改良工事', type: '公共インフラ', loc: '千葉県船橋市', year: '2025年2月', cat: '土木工事', ph: '道路工事の施工風景',
    img: 'images/excavators.jpg', gallery: ['images/excavator-rocks.jpg', 'images/viaduct.jpg', 'images/engineers-laptop.jpg'],
    structure: '道路改良 延長420m', area: '—', period: '2024年7月〜2025年2月', client: '〇〇市',
    summary: '市道の拡幅と歩道整備、排水施設の改良を行った公共工事です。通学路にあたるため、交通誘導員の配置と工程の周知を徹底しました。',
    points: ['ICT建機による高精度な施工', '通学時間帯の作業制限と誘導員の増員', '雨水排水能力の向上'] },
  { id: 6, name: '〇〇物流センター鉄骨工事', type: '物流施設', loc: '千葉県市川市', year: '2024年10月', cat: '専門工事', ph: '鉄骨建方の様子',
    img: 'images/steel-frame.jpg', gallery: ['images/steel-scaffold.jpg', 'images/tower-cranes.jpg', 'images/engineer-helmet.jpg'],
    structure: '鉄骨造 地上4階', area: '18,600㎡', period: '2024年1月〜2024年10月', client: '〇〇ロジスティクス株式会社',
    summary: '大型物流センターの鉄骨建方工事です。大スパン架構の建方精度を確保するため、計測と調整を工程ごとに繰り返しました。',
    points: ['大型クレーン2台による並行建方', '建方精度の日次計測と記録', '高所作業の安全設備を標準化'] },
  { id: 7, name: '〇〇小学校外壁・屋根改修工事', type: '教育施設', loc: '東京都江東区', year: '2024年8月', cat: '改修・リフォーム', ph: '改修後の校舎外観',
    img: 'images/steel-scaffold.jpg', gallery: ['images/team.jpg', 'images/meeting-helmet.jpg', 'images/planning-desk.jpg'],
    structure: '鉄筋コンクリート造 地上4階', area: '5,200㎡', period: '2024年7月〜2024年8月', client: '〇〇区',
    summary: '夏季休業期間を利用した校舎の外壁・屋上防水の改修工事です。短期間で品質を確保するため、事前調査と工程計画に時間をかけました。',
    points: ['赤外線調査による外壁劣化の把握', '休業期間内での確実な完工', '高耐久防水材による長寿命化'] },
  { id: 8, name: '〇〇工場基礎工事', type: '工場', loc: '茨城県つくば市', year: '2024年5月', cat: '土木工事', ph: '基礎工事の配筋',
    img: 'images/excavator-rocks.jpg', gallery: ['images/excavators.jpg', 'images/viaduct.jpg', 'images/team-review.jpg'],
    structure: '杭基礎・べた基礎', area: '7,300㎡', period: '2023年12月〜2024年5月', client: '〇〇工業株式会社',
    summary: '精密機器工場の新設に伴う基礎工事です。大型設備を支える基礎として、配筋とコンクリート品質の管理を特に重視しました。',
    points: ['配筋検査の全数写真記録', 'マスコンクリートの温度管理', '設備基礎の高精度レベル管理'] },
  { id: 9, name: '〇〇ホテル客室リノベーション工事', type: '宿泊施設', loc: '京都府京都市', year: '2024年3月', cat: '改修・リフォーム', ph: 'リノベーション後の客室',
    img: 'images/consultation.jpg', gallery: ['images/planning-desk.jpg', 'images/handshake.jpg', 'images/team-office.jpg'],
    structure: '鉄筋コンクリート造 全84室', area: '3,100㎡', period: '2023年10月〜2024年3月', client: '株式会社〇〇ホテルズ',
    summary: '営業を続けながら全84室を段階的に改装したリノベーション工事です。宿泊客への影響を抑えるため、作業時間と動線を細かく管理しました。',
    points: ['フロア単位の段階改装で営業を継続', '客室モックアップによる仕様確認', '低臭・低VOC材料の採用'] },
];
